name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

env:
  RUSTFLAGS: "-D warnings"

jobs:
  cargo_tests:
    name: ${{ matrix.os }} ${{ matrix.channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.channel }}
    - run: cargo test
    - run: cargo test --release
    - name: test k12sum
      run: cargo test
      working-directory: ./k12sum
    - name: test benchmarks
      run: cargo test --benches
      env:
        RUSTC_BOOTSTRAP: 1

  cross_tests:
    name: cross ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - i686-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          # Big-endian targets. See https://twitter.com/burntsushi5/status/1695483429997945092.
          - powerpc64-unknown-linux-gnu
          - s390x-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo install cross
    - run: cross test --target ${{ matrix.arch }}
