name: publish_k12sum_binaries

on:
  push:
    tags:
      - "*"

env:
  RUSTFLAGS: "-D warnings"

jobs:
  cargo_tests:
    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [
          { "os": "ubuntu-latest",  "rust-target": "x86_64-unknown-linux-musl", "name": "Linux" },
          { "os": "macOS-latest",   "rust-target": "aarch64-apple-darwin",      "name": "macOS" },
          { "os": "windows-latest", "rust-target": "x86_64-pc-windows-msvc",    "name": "Windows" },
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: pip install PyGithub
      - run: sudo apt-get install musl-tools
        if: matrix.target.os == 'ubuntu-latest'
      - run: rustup target add ${{ matrix.target.rust-target }}
      - name: build k12sum
        id: build_k12sum
        run: python -u .github/workflows/build_k12sum.py ${{ matrix.target.rust-target }}
      - name: upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TAG: ${{ github.ref }}
        run: python -u .github/workflows/upload_github_release_asset.py ${{ steps.build_k12sum.outputs.bin_path }}
